name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        uses: theos/setup-theos@master
      - name: Build
        run: make package FINALPACKAGE=1
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: MiDylib
          path: .theos/obj/*.dylib
